name: Continous Integration
on:
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]
jobs:
    test_flutter_app:
        name: Tests the functionslity of the flutter application
        runs-on: ubuntu-latest
        steps:
          - name: Import Required Plugins
            uses: actions/checkout
          - name: Import Java
            uses: actions/setup-java
            with:
                java-version: "12.x"
          - uses: subosito/flutter-action@v1
            with: 
                version: "stable"
          - run: flutter pub get
          - run: flutter analyze
  