name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
              java-version: "12.x"
        - uses: subosito/flutter-action@v2
          with:
              version: "stable"
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test